version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:734489868391:task-definition/spring-ms:1"
        LoadBalancerInfo:
          ContainerName: "spring-ms-services"
          ContainerPort: "80"
        PlatformVersion: "LATEST"